// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package moustacios

import (
	"database/sql"
)

type Comment struct {
	ID             int64
	Email          string
	CommentText    string
	BotProbability sql.NullInt16
}
